smtpAuth: true
smtpStartTtsEnable: true
host: "smtp.mail.yahoo.com"
port: 587
sslTrust: "smtp.mail.yahoo.com"
username: "theinvoicer12@yahoo.com"
password: "the password was changed anyway so there's no point trying!"